In [34]:
import sys
sys.path.append("../src")

import pandas as pd
from IPython.display import display, Markdown

from tickers import WATCHLIST, OWNED, sanitize_tickers
from parameters import (
    ACCOUNT_SIZE,
    RISK_PER_TRADE,
    WATCHLIST_ROWS_TO_SHOW,
    OWNED_ROWS_TO_SHOW,
)
from data_fetch import prefetch_prices
from strategy import run_prefetched


# Sanitize tickers
watchlist_clean, watch_remap, watch_drop = sanitize_tickers(WATCHLIST)
owned_clean, owned_remap, owned_drop = sanitize_tickers(OWNED)

dupes_watch = sorted({t for t in WATCHLIST if WATCHLIST.count(t) > 1})
dupes_owned = sorted({t for t in OWNED if OWNED.count(t) > 1})

if watch_remap or watch_drop or dupes_watch:
    print(
        "WATCHLIST → remapped:", watch_remap,
        "| dropped:", sorted(set(watch_drop)),
        "| duplicates removed:", dupes_watch
    )

if owned_remap or owned_drop or dupes_owned:
    print(
        "OWNED     → remapped:", owned_remap,
        "| dropped:", sorted(set(owned_drop)),
        "| duplicates removed:", dupes_owned
    )


# Fetch and score
print("Fetching prices...")
watch_cache = prefetch_prices(watchlist_clean)
owned_cache = prefetch_prices(owned_clean)

print("Scoring...")
df_watch = run_prefetched(watch_cache, ACCOUNT_SIZE, RISK_PER_TRADE)
df_owned = run_prefetched(owned_cache, ACCOUNT_SIZE, RISK_PER_TRADE)


# Display results
BASE_COLS = [
    "Ticker", "BuyScore", "SellUrgency", "RSI14", "ATR%",
    "R_Ratio", "Stop", "Target", "SuggestedShares", "Notes"
]

def show_group(name: str, df: pd.DataFrame, n=None, sort_alpha: bool = False, sorted_limit: int = 20):
    cols = [c for c in BASE_COLS if c in df.columns]
    row_cap = n if n is not None else len(df)
    disp_cap = sorted_limit

    label = "all" if n is None else f"top {row_cap}"
    df_raw = df.sort_values("Ticker").reset_index(drop=True) if sort_alpha else df
    display(Markdown(f"## {name}: Raw ({label})"))
    display(df_raw[cols].head(row_cap))

    for sort_col, ascending, label in [
        ("BuyScore", False, f"Top {disp_cap} by BuyScore"),
        ("SellUrgency", False, f"Top {disp_cap} by SellUrgency"),
        ("ATR%", True, f"Lowest {disp_cap} by ATR%"),
    ]:
        display(Markdown(f"### {name}: {label}"))
        display(
            df.sort_values(sort_col, ascending=ascending)
              .reset_index(drop=True)[cols]
              .head(disp_cap)
        )

show_group("WATCHLIST", df_watch, n=WATCHLIST_ROWS_TO_SHOW, sort_alpha=True)
show_group("OWNED", df_owned, n=OWNED_ROWS_TO_SHOW, sort_alpha=False)

WATCHLIST → remapped: {} | dropped: [] | duplicates removed: ['URA']
Fetching prices...

4 Failed downloads:
['SPR', 'PLL', 'LTHM', 'K']: YFPricesMissingError('possibly delisted; no price data found  (period=6mo) (Yahoo error = "No data found, symbol may be delisted")')

Scoring...

## WATCHLIST: Raw (all)

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,AA,51,0,60.5,6.64,1.50,60.72,75.44,10,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
1,AAL,10,65,24.1,6.54,-2.00,11.71,12.93,6000,"RSI weak (<40) | Volatile | Liquid (≥$5,000,00..."
2,AAPL,23,55,23.7,2.26,-80.54,252.99,266.15,6000,SMA20>SMA50 | RSI weak (<40) | ATR% in sweet s...
3,ABBV,51,20,40.2,2.68,10.51,219.96,237.11,40,SMA20>SMA50 | Pullback to EMA20 | ATR% in swee...
4,ABNB,68,20,54.0,3.80,5.16,126.25,139.00,28,SMA20>SMA50 | MACD>0 | RSI healthy (50–70) | P...
...,...,...,...,...,...,...,...,...,...,...
473,YETI,10,65,11.1,4.76,-2.21,40.19,44.20,6000,"RSI weak (<40) | Volatile | Liquid (≥$5,000,00..."
474,YUM,43,0,41.0,2.26,1.18,155.60,169.09,9,Close>SMA50 | SMA20>SMA50 | MACD>0 | ATR% in s...
475,ZBH,54,20,31.5,2.88,3.30,91.68,98.67,36,Close>SMA50 | SMA20>SMA50 | RSI weak (<40) | P...
476,ZM,10,55,25.1,4.64,-3.44,76.98,81.92,6000,"RSI weak (<40) | Volatile | Liquid (≥$5,000,00..."
477,ZS,25,55,53.1,5.94,-7.55,156.11,171.95,6000,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."

### WATCHLIST: Top 20 by BuyScore

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,SBUX,71,45,55.8,2.60,1.86,95.08,102.92,21,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
1,PENN,71,45,58.5,6.71,9.30,13.78,15.86,297,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
2,ABNB,68,20,54.0,3.80,5.16,126.25,139.00,28,SMA20>SMA50 | MACD>0 | RSI healthy (50–70) | P...
3,LMT,66,20,44.1,3.06,6.66,639.00,686.47,9,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
4,MKTX,66,20,47.9,2.87,3.46,176.30,194.29,14,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
5,NTST,66,20,43.1,2.14,18.00,20.07,21.30,923,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
6,FRT,66,20,44.2,2.05,2.00,104.08,110.89,26,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
7,TJX,66,20,46.2,2.39,7.52,155.03,163.47,60,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
8,HAL,66,20,40.4,3.65,4.19,33.56,36.65,100,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
9,NOC,66,0,52.5,2.87,4.32,726.17,778.25,6,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
10,HON,66,20,40.5,2.51,3.43,230.79,247.27,16,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
11,PFE,66,20,42.7,2.27,2.94,26.20,27.82,146,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
12,TGT,66,0,53.6,3.38,4.37,115.00,126.00,29,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
13,RTX,66,0,58.0,2.96,2.04,200.10,218.24,10,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
14,GILD,66,20,46.9,2.50,2.24,141.96,152.48,18,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
15,FIVE,61,20,35.5,3.92,5.81,208.81,228.28,21,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
16,MCD,61,20,43.1,1.59,1.94,321.32,337.02,11,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
17,SAM,61,20,47.8,4.00,7.11,222.65,243.20,23,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
18,PEP,61,20,25.6,2.04,5.28,156.20,165.74,39,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
19,HSY,61,20,34.5,2.19,3.23,214.99,236.66,11,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...

### WATCHLIST: Top 20 by SellUrgency

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,FMC,15,80,49.2,5.97,-22.91,13.87,15.45,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-2..."
1,ACHR,10,65,34.4,7.05,-3.57,6.47,7.36,6000,"RSI weak (<40) | Volatile | Liquid (≥$5,000,00..."
2,LULU,15,65,23.6,3.54,-2.58,165.93,175.46,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
3,TFC,15,65,27.1,3.48,-2.68,46.49,49.78,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
4,COF,15,65,34.4,3.91,-2.44,187.51,197.19,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
5,TMO,15,65,29.2,3.09,-2.43,490.57,520.07,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
6,PODD,15,65,30.5,3.58,-2.63,233.39,247.60,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
7,RMD,15,65,22.0,2.80,-2.97,240.59,260.22,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
8,EMR,15,65,25.5,3.53,-3.18,138.06,148.89,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
9,MLM,15,65,9.6,3.49,-3.01,611.52,664.23,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
10,VMC,15,65,10.2,3.32,-3.02,277.84,301.83,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
11,NKE,15,65,11.7,2.96,-2.67,56.78,60.11,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
12,GPC,15,65,18.6,3.26,-1.49,112.27,116.30,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
13,OLED,15,65,27.9,3.83,-2.38,100.18,106.51,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
14,F,15,65,13.7,3.98,-2.23,12.37,13.18,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
15,TAP,15,65,14.5,3.27,-2.04,45.08,48.18,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
16,GIS,15,65,15.3,2.88,-2.25,41.73,45.17,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
17,MKC,15,65,16.3,3.53,-2.73,62.17,69.90,6000,RSI weak (<40) | ATR% in sweet spot | Liquid (...
18,AFRM,15,65,49.6,6.02,-3.65,49.26,53.43,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-3..."
19,VERX,15,65,49.9,6.11,-3.93,13.90,15.80,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-3..."

### WATCHLIST: Lowest 20 by ATR%

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,HOLX,60,20,42.3,0.31,4.00,75.00,75.75,399,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
1,ENB,43,20,75.4,1.47,1.09,53.07,56.14,40,Close>SMA50 | SMA20>SMA50 | MACD>0 | ATR% in s...
2,XLP,54,20,25.3,1.51,2.74,83.69,88.51,46,Close>SMA50 | SMA20>SMA50 | RSI weak (<40) | P...
3,XLRE,61,20,32.5,1.52,2.15,41.98,43.87,99,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
4,IYR,61,20,32.9,1.53,2.26,96.89,101.33,44,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
5,VOO,38,20,35.8,1.53,2.71,608.25,634.03,8,RSI weak (<40) | Pullback to EMA20 | ATR% in s...
6,SPY,38,20,36.0,1.53,2.67,661.36,689.50,7,RSI weak (<40) | Pullback to EMA20 | ATR% in s...
7,VNQ,61,20,33.9,1.53,2.06,91.55,95.77,43,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
8,SO,43,20,71.2,1.55,0.80,95.29,102.18,15,Close>SMA50 | SMA20>SMA50 | MACD>0 | ATR% in s...
9,XLU,53,0,50.7,1.57,1.15,45.96,48.75,46,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
10,VTI,38,20,35.2,1.58,2.74,325.67,339.86,15,RSI weak (<40) | Pullback to EMA20 | ATR% in s...
11,VOX,43,20,45.2,1.58,2.23,184.52,194.23,19,Pullback to EMA20 | ATR% in sweet spot | Liqui...
12,MCD,61,20,43.1,1.59,1.94,321.32,337.02,11,Close>SMA50 | SMA20>SMA50 | MACD>0 | Pullback ...
13,WEC,53,0,57.6,1.65,0.78,112.92,121.79,12,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
14,DIA,38,20,26.2,1.65,5.50,466.89,489.03,17,RSI weak (<40) | Pullback to EMA20 | ATR% in s...
15,KO,38,0,34.7,1.66,1.30,75.83,80.41,30,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI weak ...
16,XLV,38,20,31.6,1.69,5.04,149.71,157.58,46,RSI weak (<40) | Pullback to EMA20 | ATR% in s...
17,DUK,43,20,71.6,1.70,0.91,128.49,137.99,12,Close>SMA50 | SMA20>SMA50 | MACD>0 | ATR% in s...
18,AEP,53,0,57.5,1.74,1.02,129.60,138.81,13,Close>SMA50 | SMA20>SMA50 | MACD>0 | RSI healt...
19,ED,60,0,69.5,1.77,0.74,109.89,119.55,10,Close>SMA50 | SMA20>SMA50 | MACD>0 | MACD bull...

## OWNED: Raw (top 15)

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,MP,48,20,51.9,6.28,5.71,58.05,66.81,45,RSI healthy (50–70) | Pullback to EMA20 | Vola...
1,UNH,48,20,61.8,2.86,1.95,277.11,301.84,7,RSI healthy (50–70) | Pullback to EMA20 | ATR%...
2,OPEN,38,0,51.3,7.09,2.73,4.91,5.91,222,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
3,AMD,33,20,37.8,4.34,123.94,196.44,213.65,435,RSI weak (<40) | Pullback to EMA20 | Volatile ...
4,HOOD,25,55,52.6,6.15,-7.93,76.50,84.75,6000,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
5,SOFI,15,65,41.2,5.72,-2.65,18.39,19.65,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-2..."

### OWNED: Top 20 by BuyScore

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,MP,48,20,51.9,6.28,5.71,58.05,66.81,45,RSI healthy (50–70) | Pullback to EMA20 | Vola...
1,UNH,48,20,61.8,2.86,1.95,277.11,301.84,7,RSI healthy (50–70) | Pullback to EMA20 | ATR%...
2,OPEN,38,0,51.3,7.09,2.73,4.91,5.91,222,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
3,AMD,33,20,37.8,4.34,123.94,196.44,213.65,435,RSI weak (<40) | Pullback to EMA20 | Volatile ...
4,HOOD,25,55,52.6,6.15,-7.93,76.50,84.75,6000,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
5,SOFI,15,65,41.2,5.72,-2.65,18.39,19.65,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-2..."

### OWNED: Top 20 by SellUrgency

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,SOFI,15,65,41.2,5.72,-2.65,18.39,19.65,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-2..."
1,HOOD,25,55,52.6,6.15,-7.93,76.50,84.75,6000,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
2,MP,48,20,51.9,6.28,5.71,58.05,66.81,45,RSI healthy (50–70) | Pullback to EMA20 | Vola...
3,UNH,48,20,61.8,2.86,1.95,277.11,301.84,7,RSI healthy (50–70) | Pullback to EMA20 | ATR%...
4,AMD,33,20,37.8,4.34,123.94,196.44,213.65,435,RSI weak (<40) | Pullback to EMA20 | Volatile ...
5,OPEN,38,0,51.3,7.09,2.73,4.91,5.91,222,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."

### OWNED: Lowest 20 by ATR%

,Ticker,BuyScore,SellUrgency,RSI14,ATR%,R_Ratio,Stop,Target,SuggestedShares,Notes
0,UNH,48,20,61.8,2.86,1.95,277.11,301.84,7,RSI healthy (50–70) | Pullback to EMA20 | ATR%...
1,AMD,33,20,37.8,4.34,123.94,196.44,213.65,435,RSI weak (<40) | Pullback to EMA20 | Volatile ...
2,SOFI,15,65,41.2,5.72,-2.65,18.39,19.65,6000,"Volatile | Liquid (≥$5,000,000) | R:R thin (-2..."
3,HOOD,25,55,52.6,6.15,-7.93,76.50,84.75,6000,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."
4,MP,48,20,51.9,6.28,5.71,58.05,66.81,45,RSI healthy (50–70) | Pullback to EMA20 | Vola...
5,OPEN,38,0,51.3,7.09,2.73,4.91,5.91,222,"RSI healthy (50–70) | Volatile | Liquid (≥$5,0..."